## Ejercicios de Numpy
___
___

1. Importa la librería de NumPy.

In [1]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

In [5]:
array_uni = np.random.randint(1, 50, (10))
array_uni

array([23, 41, 38, 36, 16, 41, 48, 34, 36, 28])

Utilizo el método np.random.randint() porque:
- Quiero que me cree valores aleatorios (por eso no uso np.array, np.ones, np.zeros o np.empty)
- Quiero que sean números más allá del 0 al 9 (por eos no uso np.arange)
- Quiero que sean números enteros (por eso no uso np.random.random_sample o np.random.rand)
___

3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [8]:
par_impar = []

for num in array_uni:
    if num % 2 == 0:
        par_impar.append('par')
    elif num % 2 != 0:
        par_impar.append('impar')

par_impar_arr = np.array(par_impar)
print(par_impar_arr)

['impar' 'impar' 'par' 'par' 'par' 'impar' 'par' 'par' 'par' 'par']


___
4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [10]:
par_impar_arr = par_impar_arr .reshape(2, 5)
par_impar_arr

array([['impar', 'impar', 'par', 'par', 'par'],
       ['impar', 'par', 'par', 'par', 'par']], dtype='<U5')

___
5. Extrae los elementos comunes de los siguientes arrays:
    ```
    python
    array1 = np.array([1,2,3,2,3,4,3,4,5,6])
    array2 = np.array([7,2,10,2,7,4,9,4,9,8])
    ```

In [11]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [12]:
comun = np.intersect1d(array1, array2)
comun

array([2, 4])

___
6. Extraed los elementos que están en el array1 pero no en el array2.

In [15]:
arr1_notarr2 = np.setdiff1d(array1, array2)
arr1_notarr2

array([1, 3, 5, 6])

___
7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [17]:
# Hago un where para ver qué posiciones son las que coinciden. Me quedo con index[0] porque devuelve un array con dos valores:
np.where(array1 == array2)[0]

array([1, 3, 5, 7])

___
8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [20]:
array_bi = np.random.randint(0, 50, (3, 5))
array_bi

array([[48, 48, 17, 18,  4],
       [12, 17, 25,  4, 40],
       [41, 10, 33, 38, 10]])

In [23]:
# Creamos las dos condiciones para facilitar la lectura del código, y luego seleccionamos el array_bi donde se cumpla alguna de las dos condiciones (son excluyentes ambas):
cond1 = array_bi < 10
cond2 = array_bi > 40

array_bi[cond1 | cond2]

array([48, 48,  4,  4, 41])

___
9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [24]:
array_dec = np.random.uniform(5, 10, size=(5, 3))
array_dec

array([[6.06619662, 7.03154384, 6.45817936],
       [5.28655379, 9.26684464, 6.66597908],
       [9.71760132, 8.01373997, 8.38637833],
       [5.30198527, 6.67072041, 8.27480601],
       [8.1835475 , 9.45577815, 7.73256381]])

___
10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

In [25]:
array_multi = np.random.randint(1, 20, (2, 4, 7))
array_multi

array([[[11,  5, 13, 13, 11,  5, 17],
        [ 9, 12,  9, 18, 14, 14, 17],
        [ 7, 13, 14,  5, 13,  3,  3],
        [19,  8, 14, 13,  5, 13, 11]],

       [[19,  5, 13,  5, 10,  3,  8],
        [13, 16, 17, 18,  7, 18, 14],
        [14,  5,  5, 15, 17,  3,  8],
        [15, 15,  3,  7, 11, 18, 14]]])

- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [26]:
array_multi_tp = np.transpose(array_multi, (1, 2, 0))
array_multi_tp

array([[[11, 19],
        [ 5,  5],
        [13, 13],
        [13,  5],
        [11, 10],
        [ 5,  3],
        [17,  8]],

       [[ 9, 13],
        [12, 16],
        [ 9, 17],
        [18, 18],
        [14,  7],
        [14, 18],
        [17, 14]],

       [[ 7, 14],
        [13,  5],
        [14,  5],
        [ 5, 15],
        [13, 17],
        [ 3,  3],
        [ 3,  8]],

       [[19, 15],
        [ 8, 15],
        [14,  3],
        [13,  7],
        [ 5, 11],
        [13, 18],
        [11, 14]]])